### ISSUE TITLE
Offset in package-list-packages

### ISSUE THREAD

**Issue by kuwze** [emacsorphanage/helm-swoop#132]
For some reason using helm-swoop in package-list-packages the links are offset by a few (usually 2-5).

**Comment by sheepduke** [comment]
I encountered the same problem today.

The cause seems to be related to caching of swoop.

How to reproduce:

1. Run command `package-list-packages`.
2. Run `swoop` and search anything. It should work properly.
3. Install any package.
4. Run `swoop` again and search for the package you just installed. The offset shows up here.

**Comment by cireu** [comment]
@sheepduke 

Do you mean like this?

![图片](https://user-images.githubusercontent.com/18224684/62991771-8bfb3480-be83-11e9-8163-9efe2659ce43.png)

It may caused by line numbers.

**Comment by sheepduke** [comment]
> Do you mean like this?
>
I cannot confirm it because I switched to Swiper later.

I installed Swoop just now and this problem seemed to be gone.

No idea why...
