### ISSUE TITLE
Case Sensitivity

### ISSUE THREAD

**Issue by xin-jin** [emacsorphanage/helm-swoop#93]
How to make the search case sensitive?

**Comment by it3ration** [comment]
I'm also curious about this, is there a way to force case-sensitive search with `helm-swoop`?

**Comment by Joseph-Riad** [comment]
I managed to get case sensitivity by forcing helm search to be case sensitive:

`(setq helm-case-fold-search nil)
(setq case-fold-search nil)`

is what you need. Note that both lines are needed since setting `helm-case-fold-search` to nil simply makes helm follow the behavior of `case-fold-search`. This works for me because I'm religious about case sensitive search; it may or may not be what you want, though.

**Comment by conao3** [comment]
Is this still an issue?
It seems to outdated this issue. Please comment if you are still facing this issue.
This issue will be closed this September.
